### ISSUE TITLE
Accordion Kadence couleur title problème

### ISSUE THREAD

**Issue by valentincharrier** [ocade-graciet-system/ocade-child-minimal#11]
Il faut commenter la ligne color dans le fichier theme-enfant/style.scss/typographie.scss

```scss
* {
  @include typo("body-m");

  caret-color: $primary-700;
  accent-color: $primary-700;
  // color: $black;
}

```
