### ISSUE TITLE
AlignWidth déborder sur les écran inférieur à 1440px.

### ISSUE THREAD

**Issue by valentincharrier** [ocade-graciet-system/ocade-child-minimal#4]
Les règles CSS n'était pas adaptées.
Le fichier à modifier se trouve dans le thème enfants et s'appelle `layout.scss`.

Voici ce qu'il faut mettre pour la règles `.alignwide`
```scss
/* Définit la largeur maximale des blocs alignwide et alignfull */
.alignwide {
  margin-left: auto;
  margin-right: auto;
  max-width: min(95vw,1280px);

  @media (min-width: 1439px) {
    max-width: $alignwide;
    margin-left: calc(
      (($alignwide - $aligncontent) / 2) * -1
    ); /* décalage pour centrer */
    margin-right: calc(
      (($alignwide - $aligncontent) / 2) * -1
    ); /* décalage pour centrer */
  }
}
```
